name: Update Variable

on:
  push:
    branches:
      - main

jobs:
  update-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository public key
        id: fetch-key
        run: |
          repo_name="NiharikaJamble/specimin"
          api_url="https://api.github.com"
          public_key_response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$api_url/repos/$repo_name/actions/variables/public-key")
          public_key=$(echo $public_key_response | jq -r .key)
          key_id=$(echo $public_key_response | jq -r .key_id)
          echo "::set-output name=public_key::$public_key"
          echo "::set-output name=key_id::$key_id"

      - name: Encrypt new value
        id: encrypt-value
        run: |
          echo "new_accuracy='88.61'"
          echo "public_key='${{ steps.fetch-key.outputs.public_key }}'"
          encrypted_value=$(echo -n "$new_accuracy" | openssl pkeyutl -encrypt -pubin -inkey <(echo "$public_key") | base64)
          echo "::set-output name=encrypted_value::$encrypted_value"

      - name: Update GitHub Actions Variable
        run: |
          repo_name="NiharikaJamble/specimin"
          api_url="https://api.github.com"
          encrypted
