name: Update Specimin Evaluation Accuracy Variable

on:
  workflow_dispatch:
    inputs:
      new_value:
        description: 'The new accuracy value to set for the variable'
        required: true
        default: '88.61'

jobs:
  update_variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Public Key
        id: fetch_public_key
        run: |
          repo_name="NiharikaJamble/specimin"
          api_url="https://api.github.com"
          token="${{ secrets.UPDATE_VARIABLE_TOKEN }}"
          public_key_response=$(curl -s -H "Authorization: token $token" "$api_url/repos/$repo_name/actions/variables/public-key")
          echo "Public key response: $public_key_response"
          echo "Public key: $(echo $public_key_response | jq -r .key)"
          echo "Key ID: $(echo $public_key_response | jq -r .key_id)"
          echo "::set-output name=public_key::$(echo $public_key_response | jq -r .key)"
          echo "::set-output name=key_id::$(echo $public_key_response | jq -r .key_id)"
      
      - name: Encrypt New Value
        id: encrypt_value
        run: |
          new_value="${{ github.event.inputs.new_value }}"
          public_key="${{ steps.fetch_public_key.outputs.public_key }}"
          key_id="${{ steps.fetch_public_key.outputs.key_id }}"
          encrypted_value=$(echo -n "$new_value" | openssl pkeyutl -encrypt -pubin -inkey <(echo "$public_key") | base64)
          echo "::set-output name=encrypted_value::$encrypted_value"
      
      - name: Update Variable
        run: |
          repo_name="NiharikaJamble/specimin"
          api_url="https://api.github.com"
          token="${{ secrets.UPDATE_VARIABLE_TOKEN }}"
          encrypted_value="${{ steps.encrypt_value.outputs.encrypted_value }}"
          key_id="${{ steps.fetch_public_key.outputs.key_id }}"
          update_response=$(curl -s -X PUT \
            -H "Authorization: token $token" \
            -H "Content-Type: application/json" \
            "$api_url/repos/$repo_name/actions/variables/LATEST_SPECIMIN_EVAL_PERCENTAGE" \
            -d "{\"encrypted_value\":\"$encrypted_value\",\"key_id\":\"$key_id\"}")
          echo "Update response: $update_response"
          if echo "$update_response" | jq -e '.message' > /dev/null; then
            echo "Error updating variable: $(echo $update_response | jq -r '.message')"
            exit 1
          fi
          echo "Variable updated successfully!"
